# Generated by Django 4.2.1 on 2023-05-29 21:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("task_manager", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="project",
            options={"ordering": ["name"]},
        ),
        migrations.AlterModelOptions(
            name="team",
            options={"ordering": ["name"]},
        ),
        migrations.RemoveField(
            model_name="project",
            name="tasks",
        ),
        migrations.AddField(
            model_name="task",
            name="project",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="task_manager.project",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="project",
            name="team",
            field=models.ManyToManyField(
                blank=True, related_name="projects", to="task_manager.team"
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="assignees",
            field=models.ManyToManyField(
                blank=True,
                related_name="assigned",
                to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
