# Generated by Django 4.2.1 on 2023-05-29 21:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("task_manager", "0003_project_tasks"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="tasks",
        ),
        migrations.AlterField(
            model_name="task",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="project",
                to="task_manager.project",
            ),
        ),
    ]
