# Generated by Django 4.2.1 on 2023-05-30 19:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("task_manager", "0007_alter_worker_groups"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="position",
            options={},
        ),
        migrations.AlterModelOptions(
            name="project",
            options={},
        ),
        migrations.AlterModelOptions(
            name="tasktype",
            options={},
        ),
        migrations.AlterModelOptions(
            name="team",
            options={},
        ),
        migrations.AlterModelOptions(
            name="worker",
            options={"verbose_name": "worker", "verbose_name_plural": "workers"},
        ),
    ]
