# # Generated by Django 4.2.1 on 2023-06-06 18:35

from django.db import migrations


def create_groups_and_permissions(apps, schema_editor) -> None:
    group = apps.get_model('auth', 'Group')
    permission = apps.get_model('auth', 'Permission')

    # Creates Basic Group
    basic_group, _ = group.objects.get_or_create(name="Basic Group")

    # Creates Team Lead Group
    team_lead_group, _ = group.objects.get_or_create(name="Team Lead Group")

    # Assign permissions to Basic Group
    basic_permissions = permission.objects.filter(
        content_type__app_label="task_manager",
        codename__in=[
            "view_task",
            "add_task",
            "change_task",
            "delete_task",
            "add_tasktype",
            "change_tasktype",
            "delete_tasktype",
            "view_tasktype",
            "view_worker",
            "view_project",
            "view_team",
        ],
    )
    basic_group.permissions.set(basic_permissions)

    # Assign permissions to Team Lead Group
    team_lead_permissions = permission.objects.filter(
        content_type__app_label="task_manager",
        codename__in=[
            "add_project",
            "change_project",
            "delete_project",
            "view_project",
            "add_task",
            "change_task",
            "delete_task",
            "view_task",
            "add_tasktype",
            "change_tasktype",
            "delete_tasktype",
            "view_tasktype",
            "add_position",
            "change_position",
            "delete_position",
            "view_position",
            "add_team",
            "change_team",
            "delete_team",
            "view_team",
            "add_worker",
            "change_worker",
            "delete_worker",
            "view_worker",
        ],
    )
    team_lead_group.permissions.set(team_lead_permissions)


class Migration(migrations.Migration):
    dependencies = [
        ("task_manager", "0012_rename_team_project_teams_alter_team_members"),
    ]

    operations = [
        migrations.RunPython(create_groups_and_permissions),
    ]
